ALTER TABLE backups ADD COLUMN temp_backup_file VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE backups ADD COLUMN storage_name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE backups ADD COLUMN backup_file VARCHAR(255) NOT NULL DEFAULT '';
