log:
  level: info
  format: json

# HTTP Server configuration
server:
  # Bind address
  address: 0.0.0.0:8000

  # Server timeouts
  timeout:
    read: 30s
    write: 30s

  # Additional logging configuration
  log:
    requests: true

# Docker configuration
docker:
  host: "unix:///var/run/docker.sock"
  version: 1.25

# Mount Manager configuration
mount:
  temp_directory: "/srv/backuper/tmp"

# Backup rules
rules:
  # Example rule to backup all MySQL databases
  - name: "localhost_mysql"

    # allow task to run for at most 3h (task WILL NOT overlap, but WILL be delayed)
    timeout: 3h

    # directory within backuper container which represents robust storage
    # (usually it should be external storage mounted over network)
    target_directory: "/srv/backups/mysql"

    # run task every 1h
    cron_spec: "@every 1h"

    # Rotation rules
    # NOTE: unfortunately `time.ParseDuration` doesn't support days and larger time period markers
    rotation_rules:
      - period: 1h
        preserve_at_most: 5
      - period: 24h # 1 day
        preserve_at_most: 2
      - period: 168h # 7 days
        preserve_at_most: 1

    # image and command to run
    image: "mysql:5.7"

    # the command to execute
    # it should put all results into $BACKUP_TARGET_DIR (only results in this directory will be saved)
    command:
      - "sh"
      - "-c"
      - "mysqldump -ubackuper -pbackuper -h 127.0.0.1 -P 3306 --all-databases > $BACKUP_TARGET_DIR/dump.sql"
